In [79]:
import numpy as np
from scipy import ndimage

circular_remap3 = [0,1,2,4,7,6,5,3]
circular_remap5 = [0,1,2,3,4,6,8,10,15,14,13,12,11,9,7,5]

#im = np.random.randint(0, 2, size=(9,9))
im = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

window = np.array([[1,1,1],
                   [1,0,1],
                   [1,1,1]])

In [82]:
def lbp_filter(x):
    """
    Local Binary Pattern Filter
    Counts number of changes from 0 to 1 in x
    """
    #remap to circular array
    if len(x) == 8:
        x = x[circular_remap3]
    elif len(x)==16:
        x = x[circular_remap5]
    #wrap array
    wrap_x     = np.empty((len(x)+1))
    wrap_x[0]  = x[-1]
    wrap_x[1:] = x
    
    print(x)
    print(wrap_x)
    
    #use abs of diff to find changes
    change_x = np.abs(wrap_x[1:] - wrap_x[:-1])
    #sum changes
    change_count = np.sum(change_x)
    return change_count

In [83]:
print(im)
res = ndimage.generic_filter(im, lbp_filter, footprint=window, mode='constant', cval=0)

print(res)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[0. 0. 0. 2. 5. 4. 0. 0.]
[0. 0. 0. 0. 2. 5. 4. 0. 0.]
[0. 0. 0. 3. 6. 5. 4. 1.]
[1. 0. 0. 0. 3. 6. 5. 4. 1.]
[0. 0. 0. 0. 0. 6. 5. 2.]
[2. 0. 0. 0. 0. 0. 6. 5. 2.]
[0. 1. 2. 5. 8. 7. 0. 0.]
[0. 0. 1. 2. 5. 8. 7. 0. 0.]
[1. 2. 3. 6. 9. 8. 7. 4.]
[4. 1. 2. 3. 6. 9. 8. 7. 4.]
[2. 3. 0. 0. 0. 9. 8. 5.]
[5. 2. 3. 0. 0. 0. 9. 8. 5.]
[0. 4. 5. 8. 0. 0. 0. 0.]
[0. 0. 4. 5. 8. 0. 0. 0. 0.]
[4. 5. 6. 9. 0. 0. 0. 7.]
[7. 4. 5. 6. 9. 0. 0. 0. 7.]
[5. 6. 0. 0. 0. 0. 0. 8.]
[8. 5. 6. 0. 0. 0. 0. 0. 8.]
[[10 12 12]
 [16 16 20]
 [16 24 18]]
